import type { Metadata } from "next";
import { Geist, JetBrains_Mono } from "next/font/google"; // Swapped Geist_Mono for JetBrains_Mono
import "./globals.css";
import Providers from "@/providers";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"]
});

// Configure the new Monospace font
const cascadiaAlternative = JetBrains_Mono({
    variable: "--font-cascadia",
    subsets: ["latin"]
});

export const metadata: Metadata = {
    title: "World Monitor Clone",
    description: "Generated by create next app"
};

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en' suppressHydrationWarning>
            {/* Added the new variable to the body class */}
            <body className={`  ${cascadiaAlternative.variable} antialiased`}>
                <Providers>{children}</Providers>
            </body>
        </html>
    );
}
